### ISSUE TITLE
Use YARP To Talk ROS Services Error

### ISSUE THREAD

**Issue by samialperen** [robotology/yarp#2311]
Hi, I am trying to follow [use yarp to talk ros services](https://www.yarp.it/yarp_with_ros_services.html) tutorial. Here is the code that I am using:
```
#include <stdio.h>
#include <stdlib.h>
#include <yarp/os/all.h>
 
 
int main(int argc, char *argv[]) {
    if (argc!=3) {
        fprintf(stderr,"Call as %s X Y\n", argv[0]);
        return 1;
    }
 
    yarp::os::Network yarp;
    yarp::os::Node node("/yarp_add_int_client");
 
    yarp::os::RpcClient client;
    if (!client.open("add_two_ints")) {
        fprintf(stderr,"Failed to open client\n");
        return 1;
    }
 
    yarp::os::Bottle msg, reply;
    msg.addInt32(atoi(argv[1]));
    msg.addInt32(atoi(argv[2]));
    if (!client.write(msg,reply)) {
        fprintf(stderr,"Failed to call service\n");
        return 1;
    }
    printf("Got %d\n", reply.get(0).asInt32());
 
    return 0;
}
```

Here is the CMakeList I have:
```
cmake_minimum_required(VERSION 3.12)
find_package(YARP COMPONENTS os rosmsg REQUIRED)
add_executable(yarp_rosserver_client)
target_sources(yarp_rosserver_client PRIVATE yarp_rosserver_client.cpp)
target_link_libraries(yarp_rosserver_client PRIVATE YARP::YARP_os YARP::YARP_init YARP::YARP_rosmsg)
# Trying the one below didn't work either
#target_link_libraries(yarp_rosserver_client PRIVATE YARP::YARP_os YARP::YARP_init)
```

I don't get any build error, but I have the following error when I try to run the command
```
$ ./yarp_rosserver_client 3 5
[INFO] |yarp.os.Port| Port /yarp_add_int_client active at tcp://192.168.0.20:10006/
Do not know anything about type 'rospy_tutorials/AddTwoInts'
Could not connect to a type server to look up type 'rospy_tutorials/AddTwoInts'
```

I was suspicious about rospy_tutorials add_two_ints_server, but it seems it is working fine. Here is the steps I took to test it:
```
$ rosrun rospy_tutorials add_two_ints_server
$ rosservice call /add_two_ints 5 8
I got the following result in the first terminal:
Returning [5 + 8 = 13] 
```

What I am missing? Thank you very much! 

**EDIT:** I found [this page](https://www.yarp.it/yarp_with_ros_existing_yarp_ports.html) and try to run 
```
$ yarpidl_rosmsg --web true --name /typ@/yarpidl
or 
$ yarpidl_rosmsg --name /typ@/yarpidl
```

But I have the following errors:
```
# terminal where rosrun rospy_tutorials add_two_ints_server
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 667, in handle
    requests = transport.receive_once()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 751, in receive_once
    raise TransportException("receive_once[%s]: DeserializationError %s"%(self.name, str(e)))
TransportException: receive_once[/add_two_ints]: DeserializationError cannot deserialize: unpack requires a string argument of length 16

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 667, in handle
    requests = transport.receive_once()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 751, in receive_once
    raise TransportException("receive_once[%s]: DeserializationError %s"%(self.name, str(e)))
TransportException: receive_once[/add_two_ints]: DeserializationError cannot deserialize: unpack requires a string argument of length 16
```
```
#Terminal where I run yarpidl_rosmsg
[INFO] |yarp.os.Port| Port /yarpidl active at tcp://192.168.0.20:10009/
[INFO] |yarp.os.Port| Port /typ-1@/yarpidl active at tcp://192.168.0.20:10008/
Unable to load msg [rospy_tutorials/AddTwoInts]: Cannot locate message [AddTwoInts] in package [rospy_tutorials] with paths [['/opt/ros/melodic/share/rospy_tutorials/msg']]
[type] File is blank: ./rospy_tutorials/AddTwoInts.msg
[type] rospy_tutorials/AddTwoInts not found. Continuing
Unable to load msg [rospy_tutorials/AddTwoInts]: Cannot locate message [AddTwoInts] in package [rospy_tutorials] with paths [['/opt/ros/melodic/share/rospy_tutorials/msg']]
[type] File is blank: ./rospy_tutorials/AddTwoInts.msg
[type] rospy_tutorials/AddTwoInts not found. Continuing
Unable to load msg [rospy_tutorials/AddTwoInts]: Cannot locate message [AddTwoInts] in package [rospy_tutorials] with paths [['/opt/ros/melodic/share/rospy_tutorials/msg']]
[type] File is blank: ./rospy_tutorials/AddTwoInts.msg
[type] rospy_tutorials/AddTwoInts not found. Continuing
Unable to load msg [rospy_tutorials/AddTwoInts]: Cannot locate message [AddTwoInts] in package [rospy_tutorials] with paths [['/opt/ros/melodic/share/rospy_tutorials/msg']]
[type] File is blank: ./rospy_tutorials/AddTwoInts.msg
[type] rospy_tutorials/AddTwoInts not found. Continuing
```

**Comment by drdanz** [comment]
I'm sorry but the examples and the documentation seem to be a bit outdated.

I just updated the examples in [example/ros](https://github.com/robotology/yarp/blob/master/example/ros), please have a look at them and see if you manage to get these working... 

CC-Issue #1585
