### ISSUE TITLE
[ubuntu] Calling Yarp from Matlab: a problem

### ISSUE THREAD

**Issue by edoardofarnioli** [robotology/yarp#309]
Attempting to call Yarp from Matlab, I followed the steps suggested in
http://wiki.icub.org/yarpdoc/yarp_swig.html
adding some advices from 
http://wiki.icub.org/images/6/63/Yarp4Matlab.pdf

Finally, calling yarp from the Matlab command window (LoadYarp;) I obtain the following error:

Java exception occurred:
java.lang.NoClassDefFoundError: yarp/Network
	at LoadYarp.<init>(LoadYarp.java:21)
Caused by: java.lang.ClassNotFoundException: yarp.Network
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
	... 1 more

Is anyone experiencing the same problem?
Is it a bug or a problem of my setup?
Ideas, hints to a solution, help, fixes are welcome

**Comment by traversaro** [comment]
Documentation to install the Java/Matlab bindings updated in https://github.com/robotology/yarp/pull/572 .
